package faultsclusteringsystem.entity;
// Generated Jul 12, 2015 5:54:20 PM by Hibernate Tools 4.3.1

/**
 * Term generated by hbm2java
 */
public class Term implements java.io.Serializable {

	private Integer idTerm;
	private Integer idUser;
	private String term;

	public Term() {
	}

	public Integer getIdTerm() {
		return this.idTerm;
	}

	public void setIdTerm(Integer idTerm) {
		this.idTerm = idTerm;
	}

	public Integer getIdUser() {
		return idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

}
