package faultsclusteringsystem.entity;
// Generated Jul 12, 2015 5:54:20 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * PersistentDocument generated by hbm2java
 */
public class PersistentDocument implements java.io.Serializable {

	private Integer idPersistentDocument;
	private Integer idUser;
	private String rawData;
	private String vector;
	private Date insertDate;

	public PersistentDocument() {
	}

	public Integer getIdPersistentDocument() {
		return this.idPersistentDocument;
	}

	public void setIdPersistentDocument(Integer idPersistentDocument) {
		this.idPersistentDocument = idPersistentDocument;
	}
	
	public Integer getIdUser() {
		return idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getRawData() {
		return this.rawData;
	}

	public void setRawData(String rawData) {
		this.rawData = rawData;
	}

	public String getVector() {
		return this.vector;
	}

	public void setVector(String vector) {
		this.vector = vector;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

}
