package faultsclusteringsystem.entity;
// Generated Jul 12, 2015 5:54:20 PM by Hibernate Tools 4.3.1

/**
 * PersistentCluster generated by hbm2java
 */
public class PersistentCluster implements java.io.Serializable {

	private Integer idPersistentCluster;
	private Integer idUser;
	private Integer idDocument;
	private String description;
	private String center;

	public PersistentCluster() {
	}

	public Integer getIdPersistentCluster() {
		return this.idPersistentCluster;
	}

	public void setIdPersistentCluster(Integer idPersistentCluster) {
		this.idPersistentCluster = idPersistentCluster;
	}

	public Integer getIdUser() {
		return idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public Integer getIdDocument() {
		return this.idDocument;
	}

	public void setIdDocument(Integer idDocument) {
		this.idDocument = idDocument;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCenter() {
		return center;
	}

	public void setCenter(String center) {
		this.center = center;
	}
}
