package faultsclusteringsystem.entity;
// Generated Jul 12, 2015 5:54:20 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer idUser;
	private String user;
	private String distanceMeasure;
	private Integer k;
	private String clusteringState;
	private String historicalClusteringState;
	private Float treshold;
	private Set persistentDocuments = new HashSet(0);
	private Set volatileClusters = new HashSet(0);
	private Set terms = new HashSet(0);
	private Set streams = new HashSet(0);
	private Set persistentClusters = new HashSet(0);
	private Set volatileDocuments = new HashSet(0);

	public User() {
	}

	public User(String user, String distanceMeasure, Integer k, String clusteringState, Set persistentDocuments,
			Set volatileClusters, Set terms, Set streams, Set persistentClusters, Set volatileDocuments) {
		this.user = user;
		this.distanceMeasure = distanceMeasure;
		this.k = k;
		this.clusteringState = clusteringState;
		this.persistentDocuments = persistentDocuments;
		this.volatileClusters = volatileClusters;
		this.terms = terms;
		this.streams = streams;
		this.persistentClusters = persistentClusters;
		this.volatileDocuments = volatileDocuments;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getDistanceMeasure() {
		return this.distanceMeasure;
	}

	public void setDistanceMeasure(String distanceMeasure) {
		this.distanceMeasure = distanceMeasure;
	}

	public Integer getK() {
		return this.k;
	}

	public void setK(Integer k) {
		this.k = k;
	}

	public String getClusteringState() {
		return this.clusteringState;
	}

	public void setClusteringState(String clusteringState) {
		this.clusteringState = clusteringState;
	}

	public Set getPersistentDocuments() {
		return this.persistentDocuments;
	}

	public void setPersistentDocuments(Set persistentDocuments) {
		this.persistentDocuments = persistentDocuments;
	}

	public Set getVolatileClusters() {
		return this.volatileClusters;
	}

	public void setVolatileClusters(Set volatileClusters) {
		this.volatileClusters = volatileClusters;
	}

	public Set getTerms() {
		return this.terms;
	}

	public void setTerms(Set terms) {
		this.terms = terms;
	}

	public Set getStreams() {
		return this.streams;
	}

	public void setStreams(Set streams) {
		this.streams = streams;
	}

	public Set getPersistentClusters() {
		return this.persistentClusters;
	}

	public void setPersistentClusters(Set persistentClusters) {
		this.persistentClusters = persistentClusters;
	}

	public Set getVolatileDocuments() {
		return this.volatileDocuments;
	}

	public void setVolatileDocuments(Set volatileDocuments) {
		this.volatileDocuments = volatileDocuments;
	}

	public Float getTreshold() {
		return treshold;
	}

	public void setTreshold(Float treshold) {
		this.treshold = treshold;
	}

	public String getHistoricalClusteringState() {
		return historicalClusteringState;
	}

	public void setHistoricalClusteringState(String historicalClusteringState) {
		this.historicalClusteringState = historicalClusteringState;
	}
}
