package faultsclusteringsystem.entity;
// Generated Jul 12, 2015 5:54:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VolatileDocument generated by hbm2java
 */
public class VolatileDocument implements java.io.Serializable {

	private Integer idVolatileDocument;
	private Integer idUser;
	private String rawData;
	private String vector;
	private Date insertDate;

	public VolatileDocument() {
	}

	public Integer getIdVolatileDocument() {
		return this.idVolatileDocument;
	}

	public void setIdVolatileDocument(Integer idVolatileDocument) {
		this.idVolatileDocument = idVolatileDocument;
	}

	public Integer getIdUser() {
		return idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getRawData() {
		return this.rawData;
	}

	public void setRawData(String rawData) {
		this.rawData = rawData;
	}

	public String getVector() {
		return this.vector;
	}

	public void setVector(String vector) {
		this.vector = vector;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

}
