package faultsclusteringsystem.entity;
// Generated Jul 12, 2015 5:54:20 PM by Hibernate Tools 4.3.1

/**
 * VolatileCluster generated by hbm2java
 */
public class VolatileCluster implements java.io.Serializable {

	private Integer idVolatileCluster;
	private Integer idUser;
	private Integer idDocument;
	private String description;
	private String center;
	
	public VolatileCluster() {
	}

	public Integer getIdVolatileCluster() {
		return this.idVolatileCluster;
	}

	public void setIdVolatileCluster(Integer idVolatileCluster) {
		this.idVolatileCluster = idVolatileCluster;
	}

	public Integer getIdUser() {
		return idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public Integer getIdDocument() {
		return idDocument;
	}

	public void setIdDocument(Integer idDocument) {
		this.idDocument = idDocument;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCenter() {
		return center;
	}

	public void setCenter(String center) {
		this.center = center;
	}
}
